title: jck
description: Software Engineer & Hacker
baseurl: ""
url: "https://jck.sh"

# Social links
social:
  github: jck4
  linkedin: jck4

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - Dockerfile
  - docker-compose.yml
  - compose-dev.yml
  - README.md
  - .git
  - .gitignore
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

# SEO settings
seo:
  title: "jck - Software Engineer and Hacker"
  description: "Personal website of jck, a Cybersecurity Specialist and Software Engineer. Explore projects, blog posts, and professional experience."
  image: "/assets/images/og-image.jpg"
  twitter:
    username: jck4
    card: summary_large_image
  open_graph:
    locale: en_US
    type: website
    site_name: jck.sh
  canonical_url: true
  json_ld: true

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/
  posts:
    output: true
    permalink: /blog/:title.html

# Default front matter
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "resume.html"
      type: "pages"
    values:
      layout: "resume"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: jck
      share: true
      comments: false

# Permalinks
permalink: /blog/:title.html

# Redirects
redirects:
  /: /projects/
  /blog/:title/: /:year/:month/:day/:title/

# Sass settings
sass:
  style: compressed
  load_paths:
    - _sass
  sass_dir: _sass 