title: jck
description: Cybersecurity Specialist & Software Engineer
baseurl: ""
url: "https://jck.sh"

# Social links
social:
  github: jck4
  linkedin: jck4

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# SEO settings
seo:
  title: "jck - Cybersecurity Specialist & Software Engineer"
  description: "Personal website of jck, a Cybersecurity Specialist and Software Engineer. Explore projects, blog posts, and professional experience."
  image: "/assets/images/og-image.jpg"
  twitter:
    username: jck4
    card: summary_large_image
  open_graph:
    locale: en_US
    type: website
    site_name: jck.sh
  canonical_url: true
  json_ld: true

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: jck
      share: true
      comments: false

# Permalinks
permalink: pretty

# Redirects
redirects:
  /: /projects/

# Sass settings
sass:
  style: compressed
  load_paths:
    - _sass
  sass_dir: _sass 