version: '3.8'

services:
  jekyll:
    build: .
    image: jck-site:latest
    container_name: jck-site
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/srv/jekyll:ro
      - jekyll-vendor:/srv/jekyll/vendor/bundle
      - jekyll-cache:/srv/jekyll/.jekyll-cache
      - jekyll-sass:/srv/jekyll/.sass-cache
    environment:
      - JEKYLL_ENV=production
      - JEKYLL_SERVE_PORT=3000
    command: bundle exec jekyll serve --host 0.0.0.0 --port 3000 --incremental

volumes:
  jekyll-vendor:
  jekyll-cache:
  jekyll-sass: 