name: Docker Compose Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and deploy with Docker Compose
        run: |
          # Build new image
          docker compose build --no-cache
          
          # Scale up to 2 containers
          docker compose up -d --scale jekyll=2
          
          # Wait for new container to be healthy
          echo "Waiting for new container to be healthy..."
          timeout=60
          while [ $timeout -gt 0 ]; do
            if curl -f "http://localhost:3001/health" > /dev/null 2>&1; then
              echo "New container is healthy!"
              break
            fi
            sleep 5
            timeout=$((timeout-5))
          done
          
          if [ $timeout -le 0 ]; then
            echo "Health check failed"
            docker compose down
            exit 1
          fi
          
          # Scale back down to 1
          docker compose up -d --scale jekyll=1 