name: Docker Compose Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and deploy with Docker Compose
        run: |
          
          # Build new images
          docker compose build --no-cache
          
          # Deploy with zero downtime
          docker compose up -d --no-deps --scale jekyll=2
          
          # Wait for new container to be healthy
          sleep 10
          
          # Remove old container
          docker compose up -d --no-deps --scale jekyll=1 